import { isStringType, nodeByteSize } from "../nodes/types";
import type { MemoryClass } from "../state/MemoryContext";
import { offsets } from "../nodes/layout";

// Convert a MemoryClass definition into a compilable C++ struct header definition.
// Handles automatic padding naming (pad_0x4[0x8]), primitive C++ types, pointers,
// fixed char arrays, and static_assert size verification.

const TYPE_MAP: Record<string, string> = {
    int8: "int8_t",
    int16: "int16_t",
    int32: "int32_t",
    int64: "int64_t",
    uint8: "uint8_t",
    uint16: "uint16_t",
    uint32: "uint32_t",
    uint64: "uint64_t",
    float: "float",
    double: "double",
    bool: "bool",
    pointer: "uintptr_t",
};

export function exportClassToCpp(cls: MemoryClass): string {
    const lines: string[] = [];
    lines.push("// Generated by web-mv");
    lines.push("#include <cstdint>");
    lines.push("");
    lines.push(`struct ${cls.name || "Class"} {`);

    const nodeOffs = offsets(cls.nodes);
    let currentOffset = 0;

    cls.nodes.forEach((node, i) => {
        const off = nodeOffs[i];
        const span = nodeByteSize(node);

        // Insert explicit padding field if there's a gap between fields
        if (off > currentOffset) {
            const padSize = off - currentOffset;
            const padHex = `0x${currentOffset.toString(16)}`;
            lines.push(
                `    uint8_t pad_${padHex}[0x${padSize.toString(16)}]; // ${padHex}`,
            );
        }

        const hexOff = `0x${off.toString(16)}`;

        if (node.typeId.startsWith("fill")) {
            // Untyped fill tile
            lines.push(`    uint8_t pad_${hexOff}[0x${span.toString(16)}]; // ${hexOff}`);
        } else if (isStringType(node.typeId)) {
            const isWide = node.typeId === "wstring";
            const charType = isWide ? "wchar_t" : "char";
            const charCount = isWide ? Math.floor(span / 2) : span;
            const name = node.name || `str_${hexOff}`;
            lines.push(`    ${charType} ${name}[${charCount}]; // ${hexOff}`);
        } else {
            const cppType = TYPE_MAP[node.typeId] || "uint8_t";
            const name = node.name || `field_${hexOff}`;
            lines.push(`    ${cppType} ${name}; // ${hexOff}`);
        }

        currentOffset = off + span;
    });

    lines.push(`};`);
    lines.push(
        `static_assert(sizeof(${cls.name || "Class"}) == 0x${currentOffset.toString(16)}, "${cls.name || "Class"} size mismatch");`,
    );

    return lines.join("\n");
}
