import { isRefType, isStringType, nodeByteSize, type Node } from "../nodes/types";
import type { MemoryClass } from "../state/MemoryContext";
import { offsets } from "../nodes/layout";

// Convert a MemoryClass definition into a compilable C++ struct header definition.
// Handles automatic padding naming (pad_0x4[0x8]), primitive C++ types, pointers,
// fixed char arrays, vectors/matrices (float arrays), function pointers, enum/struct
// references (by name, with a size comment so a missing definition is diagnosable),
// named bitfields (as a flag comment), and static_assert size verification.

const TYPE_MAP: Record<string, string> = {
    int8: "int8_t",
    int16: "int16_t",
    int32: "int32_t",
    int64: "int64_t",
    uint8: "uint8_t",
    uint16: "uint16_t",
    uint32: "uint32_t",
    uint64: "uint64_t",
    float: "float",
    double: "double",
    bool: "bool",
    pointer: "uintptr_t",
    funcptr: "uintptr_t", // call target; cast to the real signature at the use site
    bits8: "uint8_t",
    bits16: "uint16_t",
    bits32: "uint32_t",
    bits64: "uint64_t",
};

const FLOAT_COUNTS: Record<string, number> = { vec2: 2, vec3: 3, vec4: 4, mat4: 16 };

function nodeComment(node: Node, hexOff: string): string {
    const parts = [hexOff];
    if (node.endian === "be") parts.push("big-endian");
    if (node.bitNames && node.bitNames.some((b) => b)) {
        parts.push(`bits: ${node.bitNames.map((b, i) => (b ? `${i}=${b}` : "")).filter(Boolean).join(" ")}`);
    }
    return parts.join(" · ");
}

export function exportClassToCpp(cls: MemoryClass): string {
    const lines: string[] = [];
    lines.push("// Generated by web-mv");
    lines.push("#include <cstdint>");
    lines.push("");
    lines.push(`struct ${cls.name || "Class"} {`);

    const nodeOffs = offsets(cls.nodes);
    let currentOffset = 0;

    cls.nodes.forEach((node, i) => {
        const off = nodeOffs[i];
        const span = nodeByteSize(node);

        // Insert explicit padding field if there's a gap between fields
        if (off > currentOffset) {
            const padSize = off - currentOffset;
            const padHex = `0x${currentOffset.toString(16)}`;
            lines.push(
                `    uint8_t pad_${padHex}[0x${padSize.toString(16)}]; // ${padHex}`,
            );
        }

        const hexOff = `0x${off.toString(16)}`;
        const name = node.name || `field_${hexOff}`;

        if (node.typeId.startsWith("fill")) {
            // Untyped fill tile
            lines.push(`    uint8_t pad_${hexOff}[0x${span.toString(16)}]; // ${hexOff}`);
        } else if (isStringType(node.typeId)) {
            const isWide = node.typeId === "wstring";
            const charType = isWide ? "wchar_t" : "char";
            const charCount = isWide ? Math.floor(span / 2) : span;
            lines.push(`    ${charType} ${node.name || `str_${hexOff}`}[${charCount}]; // ${hexOff}`);
        } else if (node.typeId in FLOAT_COUNTS) {
            lines.push(`    float ${name}[${FLOAT_COUNTS[node.typeId]}]; // ${hexOff} (${node.typeId})`);
        } else if (node.typeId === "union4" || node.typeId === "union8") {
            const int = node.typeId === "union4" ? "int32_t" : "int64_t";
            const flt = node.typeId === "union4" ? "float" : "double";
            lines.push(`    union { ${int} as_int; ${flt} as_float; } ${name}; // ${hexOff}`);
        } else if (isRefType(node.typeId)) {
            const ref = node.refName || "Unknown";
            if (node.typeId === "enumref") {
                const underlying = span === 1 ? "int8_t" : span === 2 ? "int16_t" : span === 8 ? "int64_t" : "int32_t";
                lines.push(`    ${underlying} ${name}; // ${hexOff} (enum ${ref})`);
            } else {
                lines.push(`    ${ref} ${name}; // ${hexOff} (0x${span.toString(16)} bytes; requires ${ref} definition)`);
            }
        } else {
            const cppType = TYPE_MAP[node.typeId] || "uint8_t";
            lines.push(`    ${cppType} ${name}; // ${nodeComment(node, hexOff)}`);
        }

        currentOffset = off + span;
    });

    lines.push(`};`);
    lines.push(
        `static_assert(sizeof(${cls.name || "Class"}) == 0x${currentOffset.toString(16)}, "${cls.name || "Class"} size mismatch");`,
    );

    return lines.join("\n");
}
